UserBundle\Document\User:
    type: document

    fields:
        id:
            id: true
        username:
            type: string
        secondName:
            type: string
        email:
            type: string
            unique: true
        password:
            type: string
        enabled:
            type: boolean
