---

  - name: Install depot_tools first (needed for source checkout)
    git: repo=https://chromium.googlesource.com/chromium/tools/depot_tools.git dest=/tmp/depot_tools


  - shell: export PATH=`pwd`/depot_tools:"$PATH" && fetch v8
    args:
        chdir: /tmp

  - shell: git checkout 4.2.77
    args:
        chdir: /tmp/v8

  - shell: export PATH=`pwd`/depot_tools:"$PATH" && gclient sync
    args:
        chdir: /tmp

  - shell: make native library=shared -j8
    args:
        chdir: /tmp/v8

  - shell: "{{ item }}"
    with_items:
        - mkdir -p /usr/lib /usr/include
        - cp /tmp/v8/out/native/lib.target/lib*.so /usr/lib/
        - cp -R /tmp/v8/include/* /usr/include
    args:
        chdir: /tmp/v8

  - shell: echo -e "create /usr/lib/libv8_libplatform.a\naddlib out/native/obj.target/tools/gyp/libv8_libplatform.a\nsave\nend" | sudo ar -M
    args:
        chdir: /tmp/v8
        executable: /bin/bash