---

- name: Add keys authenticity
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7F0CEB10

- name:  Add source sources
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list

- name: Install Packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - mongodb-org


- stat: path=/etc/php5/mods-available/mongo.ini
  register: phpmongo

- name: Install php5-mongo
  include: php5-mongo.yml
  when: phpmongo.stat.exists == False