UserBundle\Document\User:
    constraints:
        - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique: email
    properties:
        email:
            - Email: ~
        plainPassword:
            - Length: {min: 6}
