/**
 * Created by ap on 21.04.15.
 */

module.exports = {
    CONFIRM_REGISTRATION: 'CONFIRM_REGISTRATION',
    REGISTRATION_FORM_CHANGED: 'REGISTRATION_FORM_CHANGED',
    REGISTRATION_CHANGED: 'REGISTRATION_CHANGED',
    REGISTRATION_FAIL: 'REGISTRATION_FAIL',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS'
};