services:
    parser_consumer:
        class: AP\ParserBundle\Rabbit\ParserConsumer

    parser:
        class: AP\ParserBundle\Parsers\Parser
        arguments:
            - @old_sound_rabbit_mq.parser_producer