---
- name: build-essential libssl-dev
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - build-essential
    - libssl-dev

- name: download nvm
  git: repo=https://github.com/creationix/nvm.git dest=/tmp/nvm

- name: install nvm
  sudo: no
  shell: /tmp/nvm/install.sh

- lineinfile: >
      dest=/home/vagrant/.profile
      line="source ~/.nvm/nvm.sh"

- name: install node
  sudo: no
  shell: bash -lc 'nvm install  0.12.2 && nvm use 0.12.2'
  args:
    executable: /bin/bash
